USE CanchaLibre;

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE CUENTA_USUARIO;
TRUNCATE TABLE CLIENTE;
TRUNCATE TABLE PROPIETARIO;
TRUNCATE TABLE ADMINISTRADOR;
TRUNCATE TABLE CANCHA;
TRUNCATE TABLE BLOQUE_HORARIO;
TRUNCATE TABLE RESERVA;
TRUNCATE TABLE COMPROBANTE;
TRUNCATE TABLE PAGO;
TRUNCATE TABLE RESENA;
TRUNCATE TABLE DETALLE_RESERVA;
TRUNCATE TABLE CANCHA_DEPORTE;
TRUNCATE TABLE CANCHA_ETIQUETA;

ALTER TABLE CUENTA_USUARIO AUTO_INCREMENT = 1;
ALTER TABLE CLIENTE AUTO_INCREMENT = 1;
ALTER TABLE PROPIETARIO AUTO_INCREMENT = 1;
ALTER TABLE ADMINISTRADOR AUTO_INCREMENT = 1;
ALTER TABLE CANCHA AUTO_INCREMENT = 1;
ALTER TABLE BLOQUE_HORARIO AUTO_INCREMENT = 1;
ALTER TABLE RESERVA AUTO_INCREMENT = 1;
ALTER TABLE COMPROBANTE AUTO_INCREMENT = 1;
ALTER TABLE PAGO AUTO_INCREMENT = 1;
ALTER TABLE RESENA AUTO_INCREMENT = 1;
ALTER TABLE DETALLE_RESERVA AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;

/*
CREATE TABLE Notificacion
CREATE TABLE NotificacionBloqueo
CREATE TABLE NotificacionReserva
CREATE TABLE NotificacionComprobante
*/