SELECT * FROM CUENTA_USUARIO;
SELECT * FROM CLIENTE;
SELECT * FROM PROPIETARIO;
SELECT * FROM ADMINISTRADOR;
SELECT * FROM CANCHA;
SELECT * FROM RESENA;
SELECT * FROM RESERVA;
SELECT * FROM PAGO;
SELECT * FROM COMPROBANTE;

DELETE FROM COMPROBANTE;
DELETE FROM PAGO;
DELETE FROM RESENA;
DELETE FROM RESERVA;
DELETE FROM CANCHA;
DELETE FROM ADMINISTRADOR;
DELETE FROM PROPIETARIO;
DELETE FROM CLIENTE;
DELETE FROM CUENTA_USUARIO;

DBCC CHECKIDENT ('COMPROBANTE', RESEED, 0);
DBCC CHECKIDENT ('PAGO', RESEED, 0);
DBCC CHECKIDENT ('RESENA', RESEED, 0);
DBCC CHECKIDENT ('RESERVA', RESEED, 0);
DBCC CHECKIDENT ('CANCHA', RESEED, 0);
DBCC CHECKIDENT ('ADMINISTRADOR', RESEED, 0);
DBCC CHECKIDENT ('PROPIETARIO', RESEED, 0);
DBCC CHECKIDENT ('CLIENTE', RESEED, 0);
DBCC CHECKIDENT ('CUENTA_USUARIO', RESEED, 0);
