USE [CanchaLibre];
GO

BEGIN TRANSACTION;

-- Romper relaciones circulares antes de eliminar
UPDATE dbo.RESERVA
SET idPago = NULL;

UPDATE dbo.PAGO
SET idComprobante = NULL;

-- Eliminar tablas dependientes primero
DELETE FROM dbo.DETALLE_RESERVA;
DELETE FROM dbo.RESENA;
DELETE FROM dbo.PAGO;
DELETE FROM dbo.COMPROBANTE;
DELETE FROM dbo.RESERVA;

DELETE FROM dbo.BLOQUE_HORARIO;
DELETE FROM dbo.CANCHA_DEPORTE;
DELETE FROM dbo.CANCHA_ETIQUETA;
DELETE FROM dbo.CANCHA;

DELETE FROM dbo.CLIENTE;
DELETE FROM dbo.PROPIETARIO;
DELETE FROM dbo.ADMINISTRADOR;
DELETE FROM dbo.CUENTA_USUARIO;

-- Reiniciar IDENTITY
DBCC CHECKIDENT ('dbo.CUENTA_USUARIO', RESEED, 0);
DBCC CHECKIDENT ('dbo.CLIENTE', RESEED, 0);
DBCC CHECKIDENT ('dbo.PROPIETARIO', RESEED, 0);
DBCC CHECKIDENT ('dbo.ADMINISTRADOR', RESEED, 0);
DBCC CHECKIDENT ('dbo.CANCHA', RESEED, 0);
DBCC CHECKIDENT ('dbo.BLOQUE_HORARIO', RESEED, 0);
DBCC CHECKIDENT ('dbo.RESERVA', RESEED, 0);
DBCC CHECKIDENT ('dbo.COMPROBANTE', RESEED, 0);
DBCC CHECKIDENT ('dbo.PAGO', RESEED, 0);
DBCC CHECKIDENT ('dbo.RESENA', RESEED, 0);
DBCC CHECKIDENT ('dbo.DETALLE_RESERVA', RESEED, 0);

COMMIT TRANSACTION;
GO