#db.tipo=MySQL
#db.host=canchalibre.clsm3doduqao.us-east-1.rds.amazonaws.com
#db.puerto=3306
#db.esquema=CanchaLibre
#db.usuario=admin
#db.password=i4NEiPFY34KbXT4FBQSOfg==
#progra320261

db.tipo=MSSQL
db.host=canchalibre-v2.ct4iuou269jv.us-east-1.rds.amazonaws.com
db.puerto=1433
db.esquema=CanchaLibre
db.usuario=admin
db.password=i4NEiPFY34KbXT4FBQSOfg==